### ISSUE TITLE
希望设置里增加方形头像和圆形头像的切换功能

### ISSUE THREAD

**Issue by Tsubamei** [ShunCai/QZoneExport#81]

**Comment by ShunCai** [comment]
没必要。

**Comment by ShunCai** [comment]
修改**QQ空间备份_QQ号\Common\css\common.css**文件，最后一行添加以下内容即可切换方形头像
``` css
/* 方形头像 */
.avatar>img,#visitors_win img,#like_win img,#visitors_html .timeline2-icon img,#friends-type-list a>img{
	border-radius:7px !important;
}
```

**Comment by Tsubamei** [comment]
感谢，测试成功。除好友列表外都已变成方形

**Comment by ShunCai** [comment]
> 感谢，测试成功。除好友列表外都已变成方形

你用的好友是表格样式吧，那没整。整的是列表样式的

**Comment by ShunCai** [comment]
替换原来那个。
``` css
/* 方形头像 */
.avatar>img,#visitors_win img,#like_win img,#visitors_html .timeline2-icon img,#friends-type-list a>img,#friends-table a>img{
	border-radius:7px !important;
}
```
